name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
    - name: Setup xvfb (Linux)
      if: runner.os == 'Linux'
      run: |
        # see https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/blob/2307c9f403c586937059d5c97e3ebc2d8769ce0d/.github/workflows/check.yml
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
        # start xvfb on (default) display :0
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - name: Install dependencies
      run: |
        conda install -n test -q -y pip setuptools setuptools_scm
    - name: Conda information
      run: |
        conda info --all
        conda list -n test
    - name: Install psrqpy
      run: |
        python -m pip install -e .[test,docs] -vv --no-build-isolation
    - name: Run test suite
      run: |
        pytest --cov=psrqpy
    - name: Test building docs
      if: ${{ matrix.os == 'ubuntu-20.04' && matrix.python-version == '3.8' }} 
      run: |
        cd docs
        mkdir source/_static
        make html
        cd ..
    - name: Upload coverage to Codecov
      if: ${{ matrix.os == 'ubuntu-20.04' && matrix.python-version == '3.8' }} 
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
        name: psrqpy

