name: Build and upload to PyPI

env:
    CIBW_SKIP: cp27-* pp27-*
    CIBW_BEFORE_BUILD: python -m pip install setuptools_scm

# Publish when a (published) GitHub Release is created:
on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build sdist and wheel
        run: |
            python -m pip install wheel setuptools setuptools_scm check-wheel-contents
            python setup.py sdist bdist_wheel --universal
            check-wheel-contents dist/*.whl
      - uses: actions/upload-artifact@v2
        with:
          path: dist/psrqpy*

  upload_pypi:
    needs: [build_dist]
    runs-on: ubuntu-latest
    # Publish when a GitHub Release is created
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
